Fix getopts ignore of options. Simplify make_tmpdir messages and other cleanup. Toggle VERSION for 0.72.

diff --git a/src/rottlog b/src/rottlog
--- a/src/rottlog
+++ b/src/rottlog
@@ -1,8 +1,7 @@
 #!/bin/bash
 # GNU Rot[t]log
-# Copyright 2001, 2002, 2003, 2004, 2005 by 
-#   Stefano Falsetto <falsetto@gnu.org>
-# Copyright 2008, 2009 by David Egan Evans <sinuhe@gnu.org>
+# Copyright 2001, 2002, 2003, 2004, 2005 Stefano Falsetto <falsetto@gnu.org>
+# Copyright 2008, 2009, 2010 David Egan Evans <sinuhe@gnu.org>
 #
 # This program is free software.  You can redistribute it, or modify it,
 # or both, under the terms of the GNU General Public License version 3
@@ -20,7 +19,7 @@
 # Suppress C-c (SIGINT) during TEMPDIR generation
 trap '' 2
 
-VERSION="0.71"
+VERSION="0.72"
 MAINDIR="$HOME/src/rottlog"
 STATDIR="/var/lib/rottlog"
 BASE_TMP_DIR="/tmp/$(basename $0)"
@@ -1469,61 +1468,57 @@ make_metapos() {
 
 # See expand_metavar and Main
 make_tmpdir () {
- # Following code was taken from:
- # checkinstall v1.4.1 (c) Felipe Eduardo Sanchez Diaz Duran (with changes)
+	# Following code was taken from (with changes):
+	# checkinstall v1.4.1 (c) Felipe Eduardo Sanchez Diaz Duran
 
- # Find a safe TEMPDIR
- [ ! -d $BASE_TMP_DIR ] && mkdir -p $BASE_TMP_DIR
+	# Find a safe TEMPDIR
+	[ ! -d $BASE_TMP_DIR ] && mkdir -p $BASE_TMP_DIR
 
- local tmpd=${BASE_TMP_DIR}/`awk 'BEGIN { srand(); for (i=1;i<21;i++) { a=95; while (a > 90 && a < 97) { a=65+int(50*rand())}; printf("%c", a) } }'`
- [ -e "$tmpd" ] && rm -rf "$tmpd"
- if [ -e "$tmpd" ]; then
-  echo
-  echo "Temp directory exists already."
-  echo "*** Aborting ***"
-  echo
-  exit 1
- fi
+	local tmpd=${BASE_TMP_DIR}/`awk 'BEGIN { srand(); for (i=1;i<21;i++) { a=95; while (a > 90 && a < 97) { a=65+int(50*rand())}; printf("%c", a) } }'`
+	[ -e "$tmpd" ] && rm -rf "$tmpd"
+	if [ -e "$tmpd" ]; then
+		echo
+		echo "Aborting: A temporary directory exists already."
+		echo
+		exit 1
+	fi
 
- mkdir $tmpd
- chmod 1700 $tmpd
- RETURN=$?
+	mkdir $tmpd
+	chmod 1700 $tmpd
+	RETURN=$?
 
- if [ $RETURN -gt 0 ]; then
-  echo
-  echo "Failed to create temp dir!"
-  echo "Do you have write permission for ${BASE_TMP_DIR}?"
-  echo
-  echo '*** Aborting ***'
-  echo
-  exit  $RETURN
- fi
+	if [ $RETURN -gt 0 ]; then
+		echo
+		echo "Failed to create ${BASE_TMP_DIR}!"
+		echo
+		exit  $RETURN
+	fi
 
- # Ignore these signals, but not critical.
- trap '' 1 2 5 6
+	# Ignore these signals, but not critical.
+	trap '' 1 2 5 6
 
- if [ -z "$1" ]; then
-  TEMPDIR="$tmpd"
-  tmpfil=$TEMPDIR/rotttempfile.$$
-  NEWtmpFILE=$TEMPDIR/rottnewtmpfile.$$
-  PURGED_FILE=$TEMPDIR/rottpurgedfile.$$
-  IFINCLUDE_FILE=$TEMPDIR/rottifincludefile.$$
-  TMPERR=$TEMPDIR/rotttemperr.$$
-  TMPERRMSG=$TEMPDIR/rotttempmsg.$$
-  MAILMSG=$TEMPDIR/rotttempmsg.$$
-  ROTATE_ATTACH=$TEMPDIR/rottateattach.$$
-  ALL_ATTACH=$TEMPDIR/rotallattach.$$
-  HANDLED=$TEMPDIR/rotthandled.$$
-  TMPROTTCOLLECT=$TEMPDIR/rottmpcollect.$$
-  TEMP_TARCOLL=$TEMPDIR/rotttarcol.$$
-  TMP_ARCH_FILE=$TEMPDIR/rotttmparchfile.$$
-  TMP_STATFILE=$TEMPDIR/rotttmpstatfile.$$
-  NEW_TMP_STATFILE=$TEMPDIR/rottnewtmpstatfile.$$
-  TMP_PERIOD_RC=$TEMPDIR/rotttmpperiodrc.$$
-  TMP_ROTTMAXAGE=$TEMPDIR/rottmaxage.$$
- else
-  eval "$1=\"$tmpd\""
- fi
+	if [ -z "$1" ]; then
+		TEMPDIR="$tmpd"
+		tmpfil=$TEMPDIR/rotttempfile.$$
+		NEWtmpFILE=$TEMPDIR/rottnewtmpfile.$$
+		PURGED_FILE=$TEMPDIR/rottpurgedfile.$$
+		IFINCLUDE_FILE=$TEMPDIR/rottifincludefile.$$
+		TMPERR=$TEMPDIR/rotttemperr.$$
+		TMPERRMSG=$TEMPDIR/rotttempmsg.$$
+		MAILMSG=$TEMPDIR/rotttempmsg.$$
+		ROTATE_ATTACH=$TEMPDIR/rottateattach.$$
+		ALL_ATTACH=$TEMPDIR/rotallattach.$$
+		HANDLED=$TEMPDIR/rotthandled.$$
+		TMPROTTCOLLECT=$TEMPDIR/rottmpcollect.$$
+		TEMP_TARCOLL=$TEMPDIR/rotttarcol.$$
+		TMP_ARCH_FILE=$TEMPDIR/rotttmparchfile.$$
+		TMP_STATFILE=$TEMPDIR/rotttmpstatfile.$$
+		NEW_TMP_STATFILE=$TEMPDIR/rottnewtmpstatfile.$$
+		TMP_PERIOD_RC=$TEMPDIR/rotttmpperiodrc.$$
+		TMP_ROTTMAXAGE=$TEMPDIR/rottmaxage.$$
+	else
+		eval "$1=\"$tmpd\""
+	fi
 }
 
 make_storefile () {
@@ -3189,7 +3184,7 @@ update_stats() {
 # MAIN
 #
 trap 'rm -rf $TEMPDIR $LOCK; exit $USCITA' 0
-debecho "MAIN: Filling time base variable"
+debecho "MAIN: Filling time base variable."
 date_refer=$(date "+%m/%d/%Y %H:%M:%S")
 # Prevent multiple executions of this program at the same time:
 if [ -e $LOCK ]; then
@@ -3253,23 +3248,11 @@ make_tmpdir
 read_rcopts "$MAINRC"
 fill_timevar "$date_refer"
 if [ $# -ne 0 ]; then
-	while getopts "dlsv" OPTS
+	while getopts "dflpsv" OPTS
 	do
 		case "$OPTS" in
 			d)
 				show_defaults
-				;;
-			l)
-				if [ -z "$NO_SHOWLOG" ]; then
-					show_log "$2"
-				fi
-				shift
-				exit 0
-				;;
-			s)
-				summarize_loginfo "$2"
-				shift
-				exit 0
 				;;
 			f)
 				if [ -z "$2" ]; then
@@ -3301,6 +3284,18 @@ if [ $# -ne 0 ]; then
 				# This was changed from --force:
 				[ "$1" = "-f" ] && config_file="none"
 				shift
+				;;
+			l)
+				if [ -z "$NO_SHOWLOG" ]; then
+					show_log "$2"
+				fi
+				shift
+				exit 0
+				;;
+			s)
+				summarize_loginfo "$2"
+				shift
+				exit 0
 				;;
 			p)
 				if [ -z "$NO_SHOWLOG" ]; then
